# Generated by Django 5.2.17 on 2026-08-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Blur'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('MULTIPLE_TABS', 'Multiple Tabs'), ('REFRESH', 'Page Refresh'), ('COPY', 'Copy Attempt'), ('PASTE', 'Paste Attempt'), ('RIGHT_CLICK', 'Right Click'), ('DEVTOOLS', 'DevTools Shortcut'), ('OTHER', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='quiz.quiz')),
            ],
            options={
                'db_table': 'violation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['participant', 'quiz'], name='violation_l_partici_3a173d_idx'), models.Index(fields=['violation_type'], name='violation_l_violati_39df00_idx'), models.Index(fields=['-created_at'], name='violation_l_created_ce9ddb_idx')],
            },
        ),
    ]
