# Generated by Django 5.2.5 on 2026-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationlog',
            name='violation_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Blur'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('MULTIPLE_TABS', 'Multiple Tabs'), ('REFRESH', 'Page Refresh'), ('COPY', 'Copy Attempt'), ('PASTE', 'Paste Attempt'), ('RIGHT_CLICK', 'Right Click'), ('DEVTOOLS', 'DevTools Shortcut'), ('EXTENSION_DETECTED', 'Browser Extension Detected'), ('MOUSE_LEAVE', 'Mouse Left Window'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
