# Generated by Django 5.2.17 on 2026-08-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='Question text')),
                ('topic', models.CharField(blank=True, default='General', max_length=200)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('description', models.TextField(blank=True, default='', help_text='Explanation shown after quiz')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('negative_marks', models.FloatField(default=0, help_text='Marks deducted for wrong answer')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A, B, C, D', max_length=5)),
                ('text', models.TextField(help_text='Option text')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
            options={
                'db_table': 'options',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Quiz duration in minutes')),
                ('total_marks', models.PositiveIntegerField(default=0, help_text='Auto-calculated from questions')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('randomize_questions', models.BooleanField(default=True, help_text='Shuffle question order per participant')),
                ('randomize_options', models.BooleanField(default=True, help_text='Shuffle option order per question per participant')),
                ('max_violations', models.PositiveIntegerField(default=3, help_text='Auto-submit after this many violations (0 = disabled)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='quiz.quiz')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('time_taken', models.FloatField(blank=True, help_text='Time taken in seconds', null=True)),
                ('score', models.FloatField(default=0)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('question_order', models.JSONField(default=list, help_text='Shuffled question ID order')),
                ('option_orders', models.JSONField(default=dict, help_text='Shuffled option orders per question')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_participations', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='quiz.quiz')),
            ],
            options={
                'db_table': 'quiz_participations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='quiz.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizparticipation')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question'], name='options_questio_6ecda2_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['status'], name='quizzes_status_ffe768_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['-created_at'], name='quizzes_created_8bd6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='questions_quiz_id_7f1263_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic'], name='questions_topic_98a2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='questions_difficu_8150ad_idx'),
        ),
        migrations.AddIndex(
            model_name='quizparticipation',
            index=models.Index(fields=['quiz', 'participant'], name='quiz_partic_quiz_id_5ea50f_idx'),
        ),
        migrations.AddIndex(
            model_name='quizparticipation',
            index=models.Index(fields=['is_submitted'], name='quiz_partic_is_subm_ec5f92_idx'),
        ),
        migrations.AddIndex(
            model_name='quizparticipation',
            index=models.Index(fields=['-score', 'time_taken'], name='quiz_partic_score_ee3df6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizparticipation',
            unique_together={('quiz', 'participant')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['participation', 'question'], name='answers_partici_aa27a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('participation', 'question')},
        ),
    ]
