# Generated by Django 5.2.17 on 2026-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_back_navigation',
            field=models.BooleanField(default=True, help_text='Allow participants to navigate back to previous questions.'),
        ),
    ]
