# Generated by Django 5.2.5 on 2026-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_allow_back_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, default='', help_text='Optional access code required for participants to enter quiz', max_length=50),
        ),
    ]
