# Generated by Django 5.2.17 on 2026-08-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/questions/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_parsed', models.PositiveIntegerField(default=0)),
                ('total_saved', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='quiz.quiz')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
