# Generated by Django 5.2.17 on 2026-08-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0, help_text='Percentage')),
                ('time_taken', models.FloatField(default=0, help_text='Seconds')),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='quiz.quiz')),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['quiz', 'rank'], name='leaderboard_quiz_id_3ce678_idx'), models.Index(fields=['-score', 'time_taken'], name='leaderboard_score_b3f2f2_idx')],
                'unique_together': {('quiz', 'participant')},
            },
        ),
    ]
